### ISSUE TITLE
Implement Email/Password Sign-In  

### ISSUE THREAD

**Issue by Shashankpantiitbhilai** [OpenLake/Centre-for-Career-Planning-and-Services-Portal#20]
Create the sign-in functionality with email and password for the student login page. Include user feedback for incorrect credentials.

**Comment by navadeep-munjam** [comment]
EXPRESS ENTHUSIASTS

**Comment by navadeep-munjam** [comment]
![Screenshot from 2024-09-01 17-19-38](https://github.com/user-attachments/assets/8ae67db5-fcfa-4c51-8e8d-418d0f3efcb7)
SignIn page completed

**Comment by Shashankpantiitbhilai** [comment]
completed
